// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageName.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "MessageName.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace msg {

namespace {

const ::google::protobuf::Descriptor* MessageName_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MessageName_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_MessageName_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_MessageName_2eproto() {
  protobuf_AddDesc_MessageName_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "MessageName.proto");
  GOOGLE_CHECK(file != NULL);
  MessageName_descriptor_ = file->message_type(0);
  static const int MessageName_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MessageName, message_name_),
  };
  MessageName_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      MessageName_descriptor_,
      MessageName::default_instance_,
      MessageName_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MessageName, _has_bits_[0]),
      -1,
      -1,
      sizeof(MessageName),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MessageName, _internal_metadata_),
      -1);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_MessageName_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      MessageName_descriptor_, &MessageName::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_MessageName_2eproto() {
  delete MessageName::default_instance_;
  delete MessageName_reflection_;
}

void protobuf_AddDesc_MessageName_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_MessageName_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\021MessageName.proto\022\003msg\"#\n\013MessageName\022"
    "\024\n\014message_name\030\001 \002(\t", 61);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "MessageName.proto", &protobuf_RegisterTypes);
  MessageName::default_instance_ = new MessageName();
  MessageName::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_MessageName_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_MessageName_2eproto {
  StaticDescriptorInitializer_MessageName_2eproto() {
    protobuf_AddDesc_MessageName_2eproto();
  }
} static_descriptor_initializer_MessageName_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int MessageName::kMessageNameFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

MessageName::MessageName()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:msg.MessageName)
}

void MessageName::InitAsDefaultInstance() {
}

MessageName::MessageName(const MessageName& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:msg.MessageName)
}

void MessageName::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  message_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MessageName::~MessageName() {
  // @@protoc_insertion_point(destructor:msg.MessageName)
  SharedDtor();
}

void MessageName::SharedDtor() {
  message_name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void MessageName::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MessageName::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MessageName_descriptor_;
}

const MessageName& MessageName::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_MessageName_2eproto();
  return *default_instance_;
}

MessageName* MessageName::default_instance_ = NULL;

MessageName* MessageName::New(::google::protobuf::Arena* arena) const {
  MessageName* n = new MessageName;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void MessageName::Clear() {
// @@protoc_insertion_point(message_clear_start:msg.MessageName)
  if (has_message_name()) {
    message_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool MessageName::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:msg.MessageName)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string message_name = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_message_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->message_name().data(), this->message_name().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "msg.MessageName.message_name");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:msg.MessageName)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:msg.MessageName)
  return false;
#undef DO_
}

void MessageName::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:msg.MessageName)
  // required string message_name = 1;
  if (has_message_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->message_name().data(), this->message_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "msg.MessageName.message_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->message_name(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:msg.MessageName)
}

::google::protobuf::uint8* MessageName::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:msg.MessageName)
  // required string message_name = 1;
  if (has_message_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->message_name().data(), this->message_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "msg.MessageName.message_name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->message_name(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:msg.MessageName)
  return target;
}

int MessageName::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:msg.MessageName)
  int total_size = 0;

  // required string message_name = 1;
  if (has_message_name()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->message_name());
  }
  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MessageName::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:msg.MessageName)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const MessageName* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const MessageName>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:msg.MessageName)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:msg.MessageName)
    MergeFrom(*source);
  }
}

void MessageName::MergeFrom(const MessageName& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:msg.MessageName)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_message_name()) {
      set_has_message_name();
      message_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.message_name_);
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void MessageName::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:msg.MessageName)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MessageName::CopyFrom(const MessageName& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:msg.MessageName)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MessageName::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void MessageName::Swap(MessageName* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MessageName::InternalSwap(MessageName* other) {
  message_name_.Swap(&other->message_name_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata MessageName::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MessageName_descriptor_;
  metadata.reflection = MessageName_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// MessageName

// required string message_name = 1;
bool MessageName::has_message_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void MessageName::set_has_message_name() {
  _has_bits_[0] |= 0x00000001u;
}
void MessageName::clear_has_message_name() {
  _has_bits_[0] &= ~0x00000001u;
}
void MessageName::clear_message_name() {
  message_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_message_name();
}
 const ::std::string& MessageName::message_name() const {
  // @@protoc_insertion_point(field_get:msg.MessageName.message_name)
  return message_name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void MessageName::set_message_name(const ::std::string& value) {
  set_has_message_name();
  message_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:msg.MessageName.message_name)
}
 void MessageName::set_message_name(const char* value) {
  set_has_message_name();
  message_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:msg.MessageName.message_name)
}
 void MessageName::set_message_name(const char* value, size_t size) {
  set_has_message_name();
  message_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:msg.MessageName.message_name)
}
 ::std::string* MessageName::mutable_message_name() {
  set_has_message_name();
  // @@protoc_insertion_point(field_mutable:msg.MessageName.message_name)
  return message_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* MessageName::release_message_name() {
  // @@protoc_insertion_point(field_release:msg.MessageName.message_name)
  clear_has_message_name();
  return message_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void MessageName::set_allocated_message_name(::std::string* message_name) {
  if (message_name != NULL) {
    set_has_message_name();
  } else {
    clear_has_message_name();
  }
  message_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), message_name);
  // @@protoc_insertion_point(field_set_allocated:msg.MessageName.message_name)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace msg

// @@protoc_insertion_point(global_scope)
